/*
 * EXT_INT_PROGRAM.c
 *
 * Created: 5/30/2021 3:22:03 AM
 *  Author: Wafaa
 */ 

#include "EXT_INT_INTERFACE.h"
#include "LED_INTERFACE.h"

void GLOB_INTERRUPT_ENABLE(void)
{
	SET_BIT(SREG,7);
}

void GLOB_INTERRUPT_DS(void)
{
	CLR_BIT(SREG,7);
}
void EXTERNAL_INTERRUPT0_INIT(void)
{
	GLOB_INTERRUPT_ENABLE();   //ENABLE FOR GLOBAL
	SET_BIT (GICR,INT0);      //ENABLE FOR PERIPHERAL INTERRUPT
	
	//TRUTH TABLE FROM MC DATASHEET
	#if EXT_INT0_STATE == EXT_INT_TRG_LOW
	CLR_BIT(MCUCR,ISC01);
	CLR_BIT(MCUCR,ISC00);
	
	#elif EXT_INT0_STATE == EXT_INT_TRG_LOGICALCHANGE
	CLR_BIT(MCUCR,ISC01);
	SET_BIT(MCUCR,ISC00);
	
	#elif EXT_INT0_STATE == EXT_INT_TRG_RISING
	SET_BIT(MCUCR,ISC01);
	CLR_BIT(MCUCR,ISC00);
	
	#elif EXT_INT0_STATE == EXT_INT_TRG_FALLING
	SET_BIT(MCUCR,ISC01);
	SET_BIT (MCUCR,ISC00);
	#endif
}
void EXTERNAL_INTERRUPT1_INIT(void)
{
	
	DIO_SetPin_Direction(DIO_PORTB, DIO_PIN0,DIO_PIN_OUTPUT);
	LED2_ON();
	
	DIO_SetPin_Direction(LED2_PORT, LED2_PIN, DIO_PIN_OUTPUT);
	DIO_SETPULLUP(LED2_PORT,LED2_PIN);
	if (GET_BIT(DIO_PORTB, DIO_PIN0)==0)
	{
		LED2_OFF();
		_delay_ms(500);
		SET_BIT(GIFR,INTF1);
	}
	//SENSE CONTROL FALLING EDGE
	CLR_BIT(MCUCR, DIO_PIN2);
	SET_BIT(MCUCR, DIO_PIN4);
	
	//GENERAL INT CONTROL REG
	SET_BIT(GICR,INT1);

}
void EXTERNAL_INTERRUPT2_INIT(void);