/*
 * KEY_PAD_PROGRAM.c
 *
 * Created: 5/30/2021 3:06:35 AM
 *  Author: Wafaa
 */ 

#include "KEY_PAD_INTERFACE.h"

const U16 KEYPAD[4][4]=
{
	/*{'1','4','7','C'},
	{'2','5','8','0'},
	{'3','6','9','='},
	{'+','-','*','/'}*/
	
	//proutes keypad	
	{'7','8','9','/'},
	{'4','5','6','*'},
	{'1','2','3','-'},
	{'c','0','=','+'}
	
};

void KEYPAD_INIT(void)
{
	//DEFINE THE DIRECTION FOR OUTPUT PIN
	DIO_SetPin_Direction(KEYPAD_PORT,KEYPAD_PIN_OUTPUT0,KEYPAD_OUTPUT);
	DIO_SetPin_Direction(KEYPAD_PORT,KEYPAD_PIN_OUTPUT1,KEYPAD_OUTPUT);
	DIO_SetPin_Direction(KEYPAD_PORT,KEYPAD_PIN_OUTPUT2,KEYPAD_OUTPUT);
	DIO_SetPin_Direction(KEYPAD_PORT,KEYPAD_PIN_OUTPUT3,KEYPAD_OUTPUT);
	
	//DEFINE DEFULTE STATE OF OUTPUT PIN
	DIO_SetPin_Value(KEYPAD_PORT,KEYPAD_PIN_OUTPUT0,KEYPAD_HIGH);
	DIO_SetPin_Value(KEYPAD_PORT,KEYPAD_PIN_OUTPUT1,KEYPAD_HIGH);
	DIO_SetPin_Value(KEYPAD_PORT,KEYPAD_PIN_OUTPUT2,KEYPAD_HIGH);
	DIO_SetPin_Value(KEYPAD_PORT,KEYPAD_PIN_OUTPUT3,KEYPAD_HIGH);
	
	//DEFINE DIRECTION OF INPUT PINS
	DIO_SetPin_Direction(KEYPAD_PORT,KEYPAD_PIN_INPUT0,KEYPAD_INPUT);
	DIO_SetPin_Direction(KEYPAD_PORT,KEYPAD_PIN_INPUT1,KEYPAD_INPUT);
	DIO_SetPin_Direction(KEYPAD_PORT,KEYPAD_PIN_INPUT2,KEYPAD_INPUT);
	DIO_SetPin_Direction(KEYPAD_PORT,KEYPAD_PIN_INPUT3,KEYPAD_INPUT);
	
	//ACTIVATE INTERNAL PULL UP
	DIO_SETPULLUP(KEYPAD_PORT,KEYPAD_PIN_INPUT0);
	DIO_SETPULLUP(KEYPAD_PORT,KEYPAD_PIN_INPUT1);
	DIO_SETPULLUP(KEYPAD_PORT,KEYPAD_PIN_INPUT2);
	DIO_SETPULLUP(KEYPAD_PORT,KEYPAD_PIN_INPUT3);
	
}

U8 KEYPAD_READ(void)
{
	U8 LOC_COL=0;
	U8 LOC_ROW=0;
	U8 Value=0;
	U8 Temp=0;
	for(LOC_COL=KEYPAD_COL_INIT;LOC_COL<= KEYPAD_COL_END;LOC_COL++)
	{
		DIO_SetPin_Value(KEYPAD_PORT,LOC_COL,KEYPAD_LOW);
		for(LOC_ROW=KEYPAD_ROW_INIT;LOC_ROW<=KEYPAD_ROW_END;LOC_ROW++)
		{
			Temp=DIO_ReadPin_Value(KEYPAD_PORT,LOC_ROW);
			if (Temp==KEYPAD_PRESSED)
			{
				Value= KEYPAD [LOC_ROW - KEYPAD_ROW_INIT][LOC_COL - KEYPAD_COL_INIT];
				while (Temp==KEYPAD_PRESSED)
				{
					Temp=DIO_ReadPin_Value(KEYPAD_PORT,LOC_ROW);
				}
				_delay_ms(10);
			}
		}
		DIO_SetPin_Value(KEYPAD_PORT,LOC_COL,KEYPAD_HIGH);
	}
	return Value;
}