/*
 * PUSH_BUTTON_PROGRAM.c
 *
 * Created: 5/30/2021 5:03:15 AM
 *  Author: Wafaa
 */ 


#include "PUSH_BUTTON_INTERFACE.h"

//BUTTON0
void BUTTON0_INIT(void)
{
	DIO_SetPin_Direction(BUTTON0_PORT,BUTTON0_PIN,DIO_PIN_INPUT);
}
void BUTTON0_PRESSED(void)
{
	DIO_SetPin_Value(BUTTON0_PORT, BUTTON0_PIN,DIO_PIN_LOW);
}

void BUTTON0_NOTPRESSED(void)
{
	DIO_SetPin_Value(BUTTON0_PORT, BUTTON0_PIN,DIO_PIN_HIGH);
}

//BUTTON1
void BUTTON1_INIT(void)
{
	DIO_SetPin_Direction(BUTTON1_PORT,BUTTON1_PIN,DIO_PIN_INPUT);
}
void BUTTON1_PRESSED(void)
{
	DIO_SetPin_Value(BUTTON1_PORT, BUTTON1_PIN,DIO_PIN_LOW);
}

void BUTTON1_NOTPRESSED(void)
{
	DIO_SetPin_Value(BUTTON1_PORT, BUTTON1_PIN,DIO_PIN_HIGH);
}

//BUTTON2
void BUTTON2_INIT(void)
{
	DIO_SetPin_Direction(BUTTON2_PORT,BUTTON2_PIN,DIO_PIN_INPUT);
}
void BUTTON2_PRESSED(void)
{
	DIO_SetPin_Value(BUTTON2_PORT, BUTTON2_PIN,DIO_PIN_LOW);
}

void BUTTON2_NOTPRESSED(void)
{
	DIO_SetPin_Value(BUTTON2_PORT, BUTTON2_PIN,DIO_PIN_HIGH);
}