/*
 * TIMER0_PROGRAM.c
 *
 * Created: 5/30/2021 3:48:10 AM
 *  Author: Wafaa
 */ 

#include "TIMER0_INTERFACE.h"

U32 NO_OVF =0;
U32 INITIAL_VALUE=0;
U32 NO_CTC=0;


void TIMER0_OVF_INIT(void)
{
	//SELECT NORMAL MODE
	CLR_BIT(TCCR0, WGM01);
	CLR_BIT(TCCR0,WGM00);
	
	SET_BIT(SREG,7);//ENABLE GLOBAL INTERRRUPT
	SET_BIT(TIMSK, TOIE0);//ENABLE PERIPHIRAL INTERRUPT
	
}
void TIMER0_OVF_START(U16 prescaler)
{
	switch (prescaler)
	{
		case CLK_8:
		CLR_BIT(TCCR0,CS02);
		SET_BIT(TCCR0,CS01);
		CLR_BIT(TCCR0,CS00);
		break;
		case CLK_64:
		CLR_BIT(TCCR0,CS02);
		SET_BIT(TCCR0,CS01);
		SET_BIT(TCCR0,CS00);
		break;
		case CLK_256:
		SET_BIT(TCCR0,CS02);
		CLR_BIT(TCCR0,CS01);
		CLR_BIT(TCCR0,CS00);
		break;
		case CLK_1024:
		SET_BIT(TCCR0,CS02);
		CLR_BIT(TCCR0,CS01);
		SET_BIT(TCCR0,CS00);
		break;
	}
}
void TIMER0_OVF_STOP(void)
{
	CLR_BIT(TCCR0,CS02);
	CLR_BIT(TCCR0,CS01);
	CLR_BIT(TCCR0,CS00);
}
void TIMER0_OVF_SET_DELAY(U32 delay)
{
	U8 Tick=1024/16;
	U32 total_count=(delay*1000)/Tick;
	NO_OVF=total_count/256;
	INITIAL_VALUE=256-(total_count % 256);
	TCNT0=INITIAL_VALUE;
	NO_OVF++;
}

void TIMER0_CTC_INIT(void)
{
	//SELECT NORMAL MODE
	SET_BIT(TCCR0, WGM01);
	CLR_BIT(TCCR0,WGM00);
	
	SET_BIT(SREG,7);//ENABLE GLOBAL INTERRRUPT
	SET_BIT(TIMSK, OCIE0);//ENABLE PERIPHIRAL INTERRUPT
	
}
void TIMER0_CTC_START(U16 prescaler)
{
	switch (prescaler)
	{
		case CLK_8:
		CLR_BIT(TCCR0,CS02);
		SET_BIT(TCCR0,CS01);
		CLR_BIT(TCCR0,CS00);
		break;
		case CLK_64:
		CLR_BIT(TCCR0,CS02);
		SET_BIT(TCCR0,CS01);
		SET_BIT(TCCR0,CS00);
		break;
		case CLK_256:
		SET_BIT(TCCR0,CS02);
		CLR_BIT(TCCR0,CS01);
		CLR_BIT(TCCR0,CS00);
		break;
		case CLK_1024:
		SET_BIT(TCCR0,CS02);
		CLR_BIT(TCCR0,CS01);
		SET_BIT(TCCR0,CS00);
		break;
	}
}
void TIMER0_CTC_STOP(void)
{
	CLR_BIT(TCCR0,CS02);
	CLR_BIT(TCCR0,CS01);
	CLR_BIT(TCCR0,CS00);
}
void TIMER0_CTC_SET_DELAY(U32 delay,U8 ocr)
{
	U8 Tick=1024/16;
	U32 total_count=(delay*1000)/Tick;
	OCR0= ocr;
	NO_CTC=total_count/OCR0;
	NO_CTC++;
}

//motor

void TIMER0_FASTPWM_INIT(void)
{
	//SET DIRECTION FOR OC0 PIN FROM DATA SHEET
	SET_BIT(DDRB,PB3);
	//SELECT PWM WAVE GENERATION
	SET_BIT(TCCR0,WGM01);
	SET_BIT(TCCR0,WGM00);
	//CHOSE INVERTING OR NON
	#if PWM_MODE == NON_INVERTING_MODE
	SET_BIT(TCCR0,COM01);
	CLR_BIT(TCCR0,COM00);
	
	#elif PWM_MODE == INVERTING_MODE
	SET_BIT(TCCR0,COM01);
	SET_BIT(TCCR0,COM00);
	
	#else
	#warning "WRONG MODE"
	
	#endif
}
void TIMER0_FASTPWM_START(void)
{
	SET_BIT(TCCR0,CS02);
	CLR_BIT(TCCR0,CS01);
	CLR_BIT(TCCR0,CS00);
}
void TIMER0_FASTPWM_SETDUTY(U8 dutycycle)
{
	#if PWM_MODE == NON_INVERTING_MODE
	OCR0=((256*dutycycle)/100)-1;
	#elif PWM_MODE == INVERTING_MODE
	OCR0=256-(((256*dutycycle)/100)-1);
	#else
	#warning "WRONG MODE"
	
	#endif
}